"""Public API for the P0 semantic kernel reference implementation."""

from .errors import (
    PatchValidationError,
    InvalidIdError,
    InvalidRelationSchemaError,
    InvalidScalarValueError,
    InvalidPatternError,
    InvalidRuleError,
    InvalidExpressionError,
    InvalidSupportError,
    InvalidVariableError,
    DerivationLimitError,
    KernelValidationError,
    MalformedPropositionError,
)
from .world import AddDirectSupport, CommitRecord, RemoveDirectSupport, Revision, World, WorldPatch
from .triggers import TriggerAdd, TriggerRule, run_trigger_phase
from .provenance import JustificationGraph, JustificationNode, why
from .canonical import canonical_argument, canonical_proposition
from .expressions import (
    BinaryExpression,
    BinaryOperator,
    Expression,
    Literal,
    UnaryExpression,
    UnaryOperator,
    VariableReference,
    evaluate_expression,
)
from .runtime import SemanticRuntime, SemanticSnapshot
from .rules import DeriveRule, derive_closure
from .maintenance import retract_support
from .defaults import DefaultRule, evaluate_defaults
from .pattern import (
    PropositionPattern,
    SupportPattern,
    Variable,
    match_conjunction,
    match_proposition,
    match_support,
)
from .support import (
    DefaultSupport,
    DerivedSupport,
    DirectSupport,
    EffectiveStatus,
    Support,
    SupportKind,
    SupportPolarity,
    default_is_defeated,
    effective_status,
)
from .model import (
    ArgumentKind,
    BooleanValue,
    KernelArgument,
    NumberValue,
    OpaqueId,
    Proposition,
    RelationSchema,
    ScalarValue,
    StringValue,
)

__all__ = [
    "ArgumentKind",
    "AddDirectSupport",
    "BooleanValue",
    "BinaryExpression",
    "BinaryOperator",
    "CommitRecord",
    "canonical_argument",
    "canonical_proposition",
    "DefaultRule",
    "DefaultSupport",
    "DerivationLimitError",
    "DeriveRule",
    "DerivedSupport",
    "DirectSupport",
    "EffectiveStatus",
    "InvalidIdError",
    "InvalidExpressionError",
    "InvalidPatternError",
    "InvalidRelationSchemaError",
    "InvalidScalarValueError",
    "InvalidRuleError",
    "InvalidSupportError",
    "InvalidVariableError",
    "KernelArgument",
    "JustificationGraph",
    "JustificationNode",
    "KernelValidationError",
    "MalformedPropositionError",
    "NumberValue",
    "Expression",
    "Literal",
    "OpaqueId",
    "PatchValidationError",
    "Proposition",
    "PropositionPattern",
    "RelationSchema",
    "RemoveDirectSupport",
    "Revision",
    "ScalarValue",
    "SemanticRuntime",
    "SemanticSnapshot",
    "StringValue",
    "SupportPolarity",
    "Support",
    "SupportKind",
    "SupportPattern",
    "TriggerAdd",
    "TriggerRule",
    "UnaryExpression",
    "UnaryOperator",
    "Variable",
    "VariableReference",
    "World",
    "WorldPatch",
    "effective_status",
    "evaluate_expression",
    "derive_closure",
    "default_is_defeated",
    "evaluate_defaults",
    "match_conjunction",
    "match_proposition",
    "match_support",
    "retract_support",
    "run_trigger_phase",
    "why",
]
